### PR TITLE
Added FlushViewOfFile button to the mapped data editor

### PR DESCRIPTION
**Pull request by jeffbromberger**
Current tool has support for FlushFileBuffers but for cases where cached IO is not used and a file mapping is created, FlushFileBuffers is a nop whereas FlushViewOfFile produces an actual Cc flush.  I debated where to put the button, but it seemed like having it in the editor was useful since the editor is modal.

### CODE REVIEW

**Comment by ladislav-zezula** [comment]
I also debated where to put the new button, but it makes the best sense to the place where you put it :-)
Thanks for the contribution, merged. I'll rebuild FileTest and will put it to my website.

**Comment by jeffbromberger** [comment]
Great!  And by the way, thank you for providing this excellent tool.  I have used it for years and this is the first time I found something it didn't do :)

**Comment by ladislav-zezula** [comment]
I am glad you like it 👍

**Comment by rodwiddowson** [comment]
Anybody who works in the FSD space loves this tool.  So I’ll add my thanks

**Pull request merged**
