### PR TITLE
Implement cmake config

### PR DESCRIPTION
**Pull request by wisemanny**
Hello, if that helps, I have made a few tweaks to the code:

1. Fixed mistypo in NtStatus2Text, there is leading "f" char.
2. Added Aaa library as git module
3. Developed cmake file that can be used to compile the binary, which I did while not having VS installed but using only msbuild. Here is the how-to:

a. cd to the root of the project, then run:
```
b. mkdir build
c. cd build
d. cmake -G "Visual Studio 17 2022" -A Win32 ../
e. cmake --build .
```
f. The file is Debug\FileTest.exe

### CODE REVIEW

**Comment by ladislav-zezula** [comment]
Hello, thanks for the contribution. I'll merge it, test and add build instructions to the README.md.

**Comment by ladislav-zezula** [comment]
In your steps to build using CMake, there's something missing. During the build, "ntdll.h" is missing.

**Comment by wisemanny** [comment]
I think I missed to add that the first step should be to add Aaa as a git submodule, from the root folder of the FileTest project run this:

git submodule add https://github.com/ladislav-zezula/Aaa.git ./lib/Aaa/

It will put the lib in the lib/Aaa folder. Please let me know if this works.

**Comment by ladislav-zezula** [comment]
Thanks!

I also did some tweaking, for example, UtilsWDK.lib is not the correct library to be used with Visual Studio build.

**Comment by wisemanny** [comment]
Good, great that it worked.

**Pull request merged**
